version: "3.8"

services:
  backend:
    image: truongcongly/backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    image: truongcongly/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
